title: ryumingi.github.io
author:
  name: Mingi Ryu

description: Knowledge representation and reasoning

remote_theme: jekyll/minima

header_pages:
  - ğŸ—ºï¸.md
  - ğŸ¸.md
  - ğŸ“–/README.md
  - ğŸ›ï¸.md
  - â›·ï¸.md
  - â­.md
  

minima:
  skin: dark
  social_links:
    - { platform: github,   user_url: "https://github.com/ryumingi" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/mryu" }

