title: ryumingi.github.io
author:
  name: Mingi Ryu

description: Knowledge representation and reasoning

remote_theme: jekyll/minima

header_pages:
  - ğŸ“–/README.md
  - â­.md
  

minima:
  skin: auto
  
  social_links:
    - { icon: github,   url: "https://github.com/ryumingi" }
    - { icon: linkedin, url: "https://www.linkedin.com/in/mryu" }

