plugins:
  - jekyll-feed

title: ryumingi.github.io
author:
  name: Mingi Ryu

description: Knowledge representation and reasoning

remote_theme: jekyll/minima

header_pages:
  - â­.md
  - ğŸ”ï¸.md
  - ğŸ”¥.md

minima:
  skin: auto
  
  social_links:
    - { icon: github,   url: "https://github.com/ryumingi" }

